---

- name: change host to /etc/hosts
  lineinfile:
    dest: /etc/hosts
   # regexp: [ \t]+localhost'
    line: '{{dspace_ip}}  dspace.{{domain}} dspace'
    state: present


- hostname:
    name: "dspace.{{domain}}"
