inventory_name:
    hosts:
       XX.XX.XX.XX:
          ansible_connection: ssh
          ansible_user: USE
          ansible_ssh_pass: 
          ansible_sudo_pass: PASS
          ansible_become: yes
          ansible_become_method: sudo
         # ansible_port: 2321