inventory_name:
    hosts:
       41.93.71.2:
          ansible_connection: ssh
          ansible_user: nitadmin
          ansible_ssh_pass: 
          ansible_sudo_pass: NIT"789!
          ansible_become: yes
          ansible_become_method: sudo